modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="cuffedwebaddon"
version="1.0"
displayName="Cuffed Web Addon"
description='''Adds web restraints for arms and legs.'''

[[dependencies.cuffedwebaddon]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cuffedwebaddon]]
    modId="thecuffed"
    mandatory=true
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"